@startuml

state START
state INIT_TCK
state INIT_NET
state INIT_XFR
state OPEN
state REQUEST_CHUNK
state RECEIVE_CHUNK
state SEND
state WAIT_TX
state WAIT_ACK
state CLOSE
state DONE

START --> INIT_TCK : true
INIT_TCK --> INIT_NET : true
INIT_NET --> INIT_XFR : true
INIT_XFR --> OPEN : true
OPEN -->  REQUEST_CHUNK : XFR.tx_opened
REQUEST_CHUNK --> DONE : XFR.eof
REQUEST_CHUNK --> RECEIVE_CHUNK : XFR.xfr_tx_valid
RECEIVE_CHUNK --> SEND : true
SEND --> WAIT_TX : NET.tx_done
WAIT_TX --> WAIT_ACK : true
WAIT_ACK --> DONE : XFR.eof
WAIT_ACK --> REQUEST_CHUNK : NET.rx_done
DONE --> CLOSE : true

note right of START
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
    },
    "_send_regs_tck": {
    }
}
end note

note right of INIT_TCK
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
    },
    "_send_regs_tck": {
        "enable": true,
        "period_ms": 100,
        "step_count": 0
    }
}
end note

note right of INIT_NET
{
    "_send_regs_net": {
        "libnet_create": true,
        "libnet_destroy": false,
        "libnet_device": "eno1",

        "eth_enabled": true,
        "eth_src_mac": "ec:b1:d7:52:8c:52",
        "eth_dst_mac": "bc:e9:2f:80:3b:56",
        "eth_type": 2048,

        "ip4_enabled": true,
        "ip4_src": "192.168.0.105",
        "ip4_dst": "192.168.0.109",
        "ip4_ttl": 64,

        "icmp4_enabled": true,
        "icmp4_type": 8,
        "icmp4_code": 0,
        "icmp4_id": 4242,
        "icmp4_seq": 0,
        "icmp4_payload": "",

        "pcap_create": true,
        "pcap_device": "eno1",
        "pcap_filter": "icmp and src host 192.168.0.109",
        "pcap_set_filter": true,
        "net_rx_enable": false

    },
    "_send_regs_xfr": {
    }
}
end note

note right of INIT_XFR
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
        "xfr_tx_open": false,
        "xfr_tx_close": false,
        "xfr_tx_path": "/usr/local/mpp/fsm/tx-file.txt",
        "xfr_tx_next": false,
        "xfr_rx_open": false,
        "xfr_rx_close": false,
        "xfr_rx_path": "/usr/local/mpp/fsm/rx-file.txt"
    }
}
end note

note right of OPEN
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
        "xfr_tx_open": true
    }
}
end note

note right of REQUEST_CHUNK
{
    "_send_regs_net": {
        "net_rx_enable": false
    },
    "_send_regs_xfr": {
        "xfr_tx_next": true
    }
}
end note

note right of RECEIVE_CHUNK
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
    }
}
end note

note right of SEND
{
    "_send_regs_net": {
        "icmp4_payload": "$XFR.buffer",
        "icmp4_seq": "$XFR.seq",
        "eof" : "$XFR.eof",
        "tx_fire": true
    },
    "_send_regs_xfr": {
    }
}
end note

note right of WAIT_TX
{
    "_send_regs_net": {
        "net_rx_enable": true,
        "rx_fire": true
    },
    "_send_regs_xfr": {
    }
}
end note

note right of WAIT_ACK
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
    }
}
end note

note right of CLOSE
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
        "xfr_tx_close": true
    }
}
end note

note right of DONE
{
    "_send_regs_net": {
    },
    "_send_regs_xfr": {
        "xfr_tx_open": false,
        "xfr_tx_close": false,
        "xfr_tx_path": "/usr/local/mpp/tx-file.txt",
        "xfr_tx_next": false,
        "xfr_rx_open": false,
        "xfr_rx_close": false,
        "xfr_rx_path": "/usr/local/mpp/rx-file.txt",
        "xfr_rx_next": false,
        "rx_seq": 0,
        "rx_buffer": "",
        "rx_len": 0
    }
}
end note

@enduml