@startuml

state IDLE
state WAIT_TX
state WAIT_RX
state DONE

IDLE --> WAIT_TX : belief FSM.intent.send
WAIT_TX --> WAIT_RX : belief NET.tx_done
WAIT_RX --> DONE : belief NET.rx_done

note right of IDLE
{
  "libnet_create": true,
  "pcap_create": true,

  "libnet_device": "eno1",
  "pcap_device": "eno1",

  "eth_enabled": true,
  "eth_src_mac": "ec:b1:d7:52:8c:52",
  "eth_dst_mac": "5c:d9:98:5f:16:54",
  "eth_type": 2048,

  "ip4_enabled": true,
  "ip4_src": "192.168.0.105",
  "ip4_dst": "192.168.0.1",
  "ip4_ttl": 64,

  "icmp4_enabled": true,
  "icmp4_type": 8,
  "icmp4_code": 0,
  "icmp4_id": 4242,
  "icmp4_seq": 0,
  "icmp4_payload": "Hello from MPP!!",

  "pcap_filter": "icmp and ether dst ec:b1:d7:52:8c:52",
  "pcap_set_filter": true,

  "tx_fire": true,
  "rx_fire": false
}
end note

note right of WAIT_TX
{
  "tx_fire": false,
  "rx_fire": true
}
end note

note right of WAIT_RX
{
  "tx_fire": false,
  "rx_fire": false
}

note right of DONE
{
  "libnet_create": false,
  "libnet_destroy": true,
  "pcap_create": false,
  "pcap_destroy": true,

  "libnet_device": "eno1",
  "pcap_device": "eno1",

  "eth_enabled": true,
  "eth_src_mac": "ec:b1:d7:52:8c:52",
  "eth_dst_mac": "5c:d9:98:5f:16:54",
  "eth_type": 2048,

  "ip4_enabled": true,
  "ip4_src": "192.168.0.105",
  "ip4_dst": "192.168.0.1",
  "ip4_ttl": 64,

  "icmp4_enabled": true,
  "icmp4_type": 8,
  "icmp4_code": 0,
  "icmp4_id": 4242,
  "icmp4_seq": 0,
  "icmp4_payload": "",

  "pcap_filter": "",
  "pcap_set_filter": false,

  "tx_fire": false,
  "rx_fire": false
}
end note

@enduml
